name: mars_scrape
channels:
  - defaults
dependencies:
  - python=3.9
  - beautifulsoup4
  - lxml
  - pandas
  - selenium
  - flask
  - pip
  - pip:
    - splinter
    - webdriver-manager
    - pymongo
    - ua-parser
